"""initial schema"""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('leads',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('phone',sa.String(32),nullable=False),sa.Column('name',sa.String(200)),sa.Column('company',sa.String(200)),sa.Column('notes',sa.Text(),nullable=False,server_default=''),sa.Column('status',sa.String(32),nullable=False,server_default='NEW'),sa.Column('result',sa.String(100)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('next_call_at',sa.DateTime(timezone=True)),sa.Column('last_call_at',sa.DateTime(timezone=True)),sa.Column('attempts',sa.Integer(),nullable=False,server_default='0'),sa.UniqueConstraint('phone'))
    op.create_index('ix_leads_phone','leads',['phone']); op.create_index('ix_leads_status','leads',['status']); op.create_index('ix_leads_next_call_at','leads',['next_call_at'])
    op.create_table('campaigns',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('description',sa.Text(),nullable=False,server_default=''),sa.Column('agent_prompt',sa.Text(),nullable=False,server_default=''),sa.Column('status',sa.String(32),nullable=False,server_default='DRAFT'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('stopped_at',sa.DateTime(timezone=True)),sa.Column('compliance_confirmed_at',sa.DateTime(timezone=True)))
    op.create_index('ix_campaigns_status','campaigns',['status'])
    op.create_table('campaign_leads',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('campaign_id',sa.Integer(),sa.ForeignKey('campaigns.id',ondelete='CASCADE'),nullable=False),sa.Column('lead_id',sa.Integer(),sa.ForeignKey('leads.id',ondelete='CASCADE'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('campaign_id','lead_id',name='uq_campaign_lead'))
    op.create_index('ix_campaign_leads_campaign_id','campaign_leads',['campaign_id']); op.create_index('ix_campaign_leads_lead_id','campaign_leads',['lead_id'])
    op.create_table('calls',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('lead_id',sa.Integer(),sa.ForeignKey('leads.id'),nullable=False),sa.Column('campaign_id',sa.Integer(),sa.ForeignKey('campaigns.id')),sa.Column('phone',sa.String(32),nullable=False),sa.Column('twilio_call_sid',sa.String(80)),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('answered_at',sa.DateTime(timezone=True)),sa.Column('ended_at',sa.DateTime(timezone=True)),sa.Column('duration',sa.Integer(),nullable=False,server_default='0'),sa.Column('status',sa.String(32),nullable=False),sa.Column('result',sa.String(64)),sa.Column('summary',sa.Text(),nullable=False,server_default=''),sa.Column('stt_ms',sa.Float(),nullable=False,server_default='0'),sa.Column('llm_ms',sa.Float(),nullable=False,server_default='0'),sa.Column('tts_ms',sa.Float(),nullable=False,server_default='0'),sa.Column('total_ms',sa.Float(),nullable=False,server_default='0'))
    op.create_index('ix_calls_lead_id','calls',['lead_id']); op.create_index('ix_calls_campaign_id','calls',['campaign_id'])
    op.create_table('transcript_messages',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('call_id',sa.Integer(),sa.ForeignKey('calls.id',ondelete='CASCADE'),nullable=False),sa.Column('role',sa.String(20),nullable=False),sa.Column('content',sa.Text(),nullable=False),sa.Column('timestamp',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_transcript_messages_call_id','transcript_messages',['call_id'])
    op.create_table('callbacks',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('lead_id',sa.Integer(),sa.ForeignKey('leads.id'),nullable=False),sa.Column('call_id',sa.Integer(),sa.ForeignKey('calls.id')),sa.Column('reason',sa.Text(),nullable=False,server_default=''),sa.Column('scheduled_at',sa.DateTime(timezone=True),nullable=False),sa.Column('status',sa.String(32),nullable=False,server_default='SCHEDULED'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_callbacks_lead_id','callbacks',['lead_id']); op.create_index('ix_callbacks_scheduled_at','callbacks',['scheduled_at'])
    op.create_table('app_settings',sa.Column('key',sa.String(100),primary_key=True),sa.Column('value',sa.Text(),nullable=False,server_default=''),sa.Column('secret',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('type',sa.String(80),nullable=False),sa.Column('payload',sa.Text(),nullable=False,server_default='{}'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False)); op.create_index('ix_events_type','events',['type'])

def downgrade():
    for t in ['events','app_settings','callbacks','transcript_messages','calls','campaign_leads','campaigns','leads']: op.drop_table(t)
